builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/oscli/main.go
    goarch:
    - amd64
    goos:
      - windows
      - darwin
      - linux
archive:
  replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .Tag }}-{{ .Commit }}"
changelog:
  sort: asc